[theme]
primaryColor = "#4F46E5"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E293B"
textColor = "#FFFFFF"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
